(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val config_create : body:Config_create_request.t -> unit -> Id_response.t Lwt.t
val config_delete : id:string -> unit Lwt.t
val config_inspect : id:string -> Config.t Lwt.t
val config_list : ?filters:string -> unit -> Config.t list Lwt.t
val config_update : id:string -> version:int64 -> body:Config_spec.t -> unit -> unit Lwt.t
