(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val container_archive : id:string -> path:string -> unit Lwt.t
val container_archive_info : id:string -> path:string -> unit Lwt.t
val container_attach : id:string -> ?detach_keys:string -> ?logs:bool -> ?stream:bool -> ?stdin:bool -> ?stdout:bool -> ?stderr:bool -> unit -> unit Lwt.t
val container_attach_websocket : id:string -> ?detach_keys:string -> ?logs:bool -> ?stream:bool -> unit -> unit Lwt.t
val container_changes : id:string -> Container_change_response_item.t list Lwt.t
val container_create : body:Container_create_request.t -> ?name:string -> unit -> Container_create_response.t Lwt.t
val container_delete : id:string -> ?v:bool -> ?force:bool -> ?link:bool -> unit -> unit Lwt.t
val container_export : id:string -> unit Lwt.t
val container_inspect : id:string -> ?size:bool -> unit -> Container_inspect_response.t Lwt.t
val container_kill : id:string -> ?signal:string -> unit -> unit Lwt.t
val container_list : ?all:bool -> ?limit:int32 -> ?size:bool -> ?filters:string -> unit -> Container_summary.t list Lwt.t
val container_logs : id:string -> ?follow:bool -> ?stdout:bool -> ?stderr:bool -> ?since:int32 -> ?until:int32 -> ?timestamps:bool -> ?tail:string -> unit -> string Lwt.t
val container_pause : id:string -> unit Lwt.t
val container_prune : ?filters:string -> unit -> Container_prune_response.t Lwt.t
val container_rename : id:string -> name:string -> unit Lwt.t
val container_resize : id:string -> ?h:int32 -> ?w:int32 -> unit -> unit Lwt.t
val container_restart : id:string -> ?t:int32 -> unit -> unit Lwt.t
val container_start : id:string -> ?detach_keys:string -> unit -> unit Lwt.t
val container_stats : id:string -> ?stream:bool -> ?one_shot:bool -> unit -> Yojson.Safe.t Lwt.t
val container_stop : id:string -> ?t:int32 -> unit -> unit Lwt.t
val container_top : id:string -> ?ps_args:string -> unit -> Container_top_response.t Lwt.t
val container_unpause : id:string -> unit Lwt.t
val container_update : id:string -> update:Container_update_request.t -> Container_update_response.t Lwt.t
val container_wait : id:string -> ?condition:Enums.condition_0 -> unit -> Container_wait_response.t Lwt.t
val put_container_archive : id:string -> path:string -> input_stream:string -> ?no_overwrite_dir_non_dir:string -> ?copy_uidgid:string -> unit -> unit Lwt.t
