(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val distribution_inspect : name:string -> Distribution_inspect.t Lwt.t
