(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val container_exec : id:string -> exec_config:Exec_config.t -> Id_response.t Lwt.t
val exec_inspect : id:string -> Exec_inspect_response.t Lwt.t
val exec_resize : id:string -> ?h:int32 -> ?w:int32 -> unit -> unit Lwt.t
val exec_start : id:string -> exec_start_config:Exec_start_config.t -> unit -> unit Lwt.t
