(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val network_connect : id:string -> container:Network_disconnect_request.t -> unit Lwt.t
val network_create : network_config:Network_create_request.t -> Network_create_response.t Lwt.t
val network_delete : id:string -> unit Lwt.t
val network_disconnect : id:string -> container:Network_connect_request.t -> unit Lwt.t
val network_inspect : id:string -> ?verbose:bool -> ?scope:string -> unit -> Network.t Lwt.t
val network_list : ?filters:string -> unit -> Network.t list Lwt.t
val network_prune : ?filters:string -> unit -> Network_prune_response.t Lwt.t
