(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let node_delete ~id ?(force = false) () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/nodes/{id}" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "id" (fun x -> x) id in
    let uri = Request.add_query_param uri "force" string_of_bool force in
    Cohttp_lwt_unix.Client.call `DELETE uri ~headers >>= fun (resp, body) ->
    Request.handle_unit_response resp

let node_inspect ~id =
    let open Lwt.Infix in
    let uri = Request.build_uri "/nodes/{id}" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "id" (fun x -> x) id in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Node.of_yojson) resp body

let node_list ?filters () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/nodes" in
    let headers = Request.default_headers in
    let uri = Request.maybe_add_query_param uri "filters" (fun x -> x) filters in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as_list_of (JsonSupport.unwrap Node.of_yojson) resp body

let node_update ~id ~version ~body () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/nodes/{id}/update" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "id" (fun x -> x) id in
    let uri = Request.add_query_param uri "version" Int64.to_string version in
    let body = Request.write_as_json_body Node_spec.to_yojson body in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.handle_unit_response resp

