(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val node_delete : id:string -> ?force:bool -> unit -> unit Lwt.t
val node_inspect : id:string -> Node.t Lwt.t
val node_list : ?filters:string -> unit -> Node.t list Lwt.t
val node_update : id:string -> version:int64 -> body:Node_spec.t -> unit -> unit Lwt.t
