(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val get_plugin_privileges : remote:string -> Plugin_privilege.t list Lwt.t
val plugin_create : name:string -> tar_context:string -> unit -> unit Lwt.t
val plugin_delete : name:string -> ?force:bool -> unit -> Plugin.t Lwt.t
val plugin_disable : name:string -> unit Lwt.t
val plugin_enable : name:string -> ?timeout:int32 -> unit -> unit Lwt.t
val plugin_inspect : name:string -> Plugin.t Lwt.t
val plugin_list : ?filters:string -> unit -> Plugin.t list Lwt.t
val plugin_pull : remote:string -> ?name:string -> ?x_registry_auth:string -> body:Plugin_privilege.t list -> unit -> unit Lwt.t
val plugin_push : name:string -> unit Lwt.t
val plugin_set : name:string -> body:string list -> unit -> unit Lwt.t
val plugin_upgrade : name:string -> remote:string -> ?x_registry_auth:string -> body:Plugin_privilege.t list -> unit -> unit Lwt.t
