(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val secret_create : body:Secret_create_request.t -> unit -> Id_response.t Lwt.t
val secret_delete : id:string -> unit Lwt.t
val secret_inspect : id:string -> Secret.t Lwt.t
val secret_list : ?filters:string -> unit -> Secret.t list Lwt.t
val secret_update : id:string -> version:int64 -> body:Secret_spec.t -> unit -> unit Lwt.t
