(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let service_create ~body ?x_registry_auth () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/services/create" in
    let headers = Request.default_headers in
    let headers = Request.maybe_add_header headers "X-Registry-Auth" (fun x -> x) x_registry_auth in
    let body = Request.write_as_json_body Service_create_request.to_yojson body in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Service_create_response.of_yojson) resp body

let service_delete ~id =
    let open Lwt.Infix in
    let uri = Request.build_uri "/services/{id}" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "id" (fun x -> x) id in
    Cohttp_lwt_unix.Client.call `DELETE uri ~headers >>= fun (resp, body) ->
    Request.handle_unit_response resp

let service_inspect ~id ?(insert_defaults = false) () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/services/{id}" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "id" (fun x -> x) id in
    let uri = Request.add_query_param uri "insertDefaults" string_of_bool insert_defaults in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Service.of_yojson) resp body

let service_list ?filters ?status () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/services" in
    let headers = Request.default_headers in
    let uri = Request.maybe_add_query_param uri "filters" (fun x -> x) filters in
    let uri = Request.maybe_add_query_param uri "status" string_of_bool status in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as_list_of (JsonSupport.unwrap Service.of_yojson) resp body

let service_logs ~id ?(details = false) ?(follow = false) ?(stdout = false) ?(stderr = false) ?(since = 0l) ?(timestamps = false) ?(tail = "all") () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/services/{id}/logs" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "id" (fun x -> x) id in
    let uri = Request.add_query_param uri "details" string_of_bool details in
    let uri = Request.add_query_param uri "follow" string_of_bool follow in
    let uri = Request.add_query_param uri "stdout" string_of_bool stdout in
    let uri = Request.add_query_param uri "stderr" string_of_bool stderr in
    let uri = Request.add_query_param uri "since" Int32.to_string since in
    let uri = Request.add_query_param uri "timestamps" string_of_bool timestamps in
    let uri = Request.add_query_param uri "tail" (fun x -> x) tail in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.to_string) resp body

let service_update ~id ~version ~body ?(registry_auth_from = `Spec) ?rollback ?x_registry_auth () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/services/{id}/update" in
    let headers = Request.default_headers in
    let headers = Request.maybe_add_header headers "X-Registry-Auth" (fun x -> x) x_registry_auth in
    let uri = Request.replace_path_param uri "id" (fun x -> x) id in
    let uri = Request.add_query_param uri "version" Int32.to_string version in
    let uri = Request.add_query_param uri "registryAuthFrom" Enums.show_registryauthfrom registry_auth_from in
    let uri = Request.maybe_add_query_param uri "rollback" (fun x -> x) rollback in
    let body = Request.write_as_json_body Service_update_request.to_yojson body in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Service_update_response.of_yojson) resp body

