(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val service_create : body:Service_create_request.t -> ?x_registry_auth:string -> unit -> Service_create_response.t Lwt.t
val service_delete : id:string -> unit Lwt.t
val service_inspect : id:string -> ?insert_defaults:bool -> unit -> Service.t Lwt.t
val service_list : ?filters:string -> ?status:bool -> unit -> Service.t list Lwt.t
val service_logs : id:string -> ?details:bool -> ?follow:bool -> ?stdout:bool -> ?stderr:bool -> ?since:int32 -> ?timestamps:bool -> ?tail:string -> unit -> string Lwt.t
val service_update : id:string -> version:int32 -> body:Service_update_request.t -> ?registry_auth_from:Enums.registryauthfrom -> ?rollback:string -> ?x_registry_auth:string -> unit -> Service_update_response.t Lwt.t
