(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val swarm_init : body:Swarm_init_request.t -> string Lwt.t
val swarm_inspect : unit -> Swarm.t Lwt.t
val swarm_join : body:Swarm_join_request.t -> unit Lwt.t
val swarm_leave : ?force:bool -> unit -> unit Lwt.t
val swarm_unlock : body:Swarm_unlock_request.t -> unit Lwt.t
val swarm_unlockkey : unit -> Unlock_key_response.t Lwt.t
val swarm_update : version:int64 -> body:Swarm_spec.t -> ?rotate_worker_token:bool -> ?rotate_manager_token:bool -> ?rotate_manager_unlock_key:bool -> unit -> unit Lwt.t
