(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val system_auth : auth_config:Auth_config.t -> unit -> System_auth_response.t Lwt.t
val system_data_usage : unit -> System_data_usage_response.t Lwt.t
val system_events : ?since:string -> ?until:string -> ?filters:string -> unit -> Event_message.t Lwt.t
val system_info : unit -> System_info.t Lwt.t
val system_ping : unit -> string Lwt.t
val system_ping_head : unit -> string Lwt.t
val system_version : unit -> System_version.t Lwt.t
