(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let system_auth ~auth_config () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/auth" in
    let headers = Request.default_headers in
    let body = Request.write_as_json_body Auth_config.to_yojson auth_config in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap System_auth_response.of_yojson) resp body

let system_data_usage () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/system/df" in
    let headers = Request.default_headers in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap System_data_usage_response.of_yojson) resp body

let system_events ?since ?until ?filters () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/events" in
    let headers = Request.default_headers in
    let uri = Request.maybe_add_query_param uri "since" (fun x -> x) since in
    let uri = Request.maybe_add_query_param uri "until" (fun x -> x) until in
    let uri = Request.maybe_add_query_param uri "filters" (fun x -> x) filters in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Event_message.of_yojson) resp body

let system_info () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/info" in
    let headers = Request.default_headers in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap System_info.of_yojson) resp body

let system_ping () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/_ping" in
    let headers = Request.default_headers in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.to_string) resp body

let system_ping_head () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/_ping" in
    let headers = Request.default_headers in
    Cohttp_lwt_unix.Client.call `HEAD uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.to_string) resp body

let system_version () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/version" in
    let headers = Request.default_headers in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap System_version.of_yojson) resp body

