(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let task_inspect ~id =
    let open Lwt.Infix in
    let uri = Request.build_uri "/tasks/{id}" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "id" (fun x -> x) id in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Task.of_yojson) resp body

let task_list ?filters () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/tasks" in
    let headers = Request.default_headers in
    let uri = Request.maybe_add_query_param uri "filters" (fun x -> x) filters in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as_list_of (JsonSupport.unwrap Task.of_yojson) resp body

let task_logs ~id ?(details = false) ?(follow = false) ?(stdout = false) ?(stderr = false) ?(since = 0l) ?(timestamps = false) ?(tail = "all") () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/tasks/{id}/logs" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "id" (fun x -> x) id in
    let uri = Request.add_query_param uri "details" string_of_bool details in
    let uri = Request.add_query_param uri "follow" string_of_bool follow in
    let uri = Request.add_query_param uri "stdout" string_of_bool stdout in
    let uri = Request.add_query_param uri "stderr" string_of_bool stderr in
    let uri = Request.add_query_param uri "since" Int32.to_string since in
    let uri = Request.add_query_param uri "timestamps" string_of_bool timestamps in
    let uri = Request.add_query_param uri "tail" (fun x -> x) tail in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.to_string) resp body

