(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val task_inspect : id:string -> Task.t Lwt.t
val task_list : ?filters:string -> unit -> Task.t list Lwt.t
val task_logs : id:string -> ?details:bool -> ?follow:bool -> ?stdout:bool -> ?stderr:bool -> ?since:int32 -> ?timestamps:bool -> ?tail:string -> unit -> string Lwt.t
