(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let volume_create ~volume_config =
    let open Lwt.Infix in
    let uri = Request.build_uri "/volumes/create" in
    let headers = Request.default_headers in
    let body = Request.write_as_json_body Volume_create_options.to_yojson volume_config in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Volume.of_yojson) resp body

let volume_delete ~name ?(force = false) () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/volumes/{name}" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    let uri = Request.add_query_param uri "force" string_of_bool force in
    Cohttp_lwt_unix.Client.call `DELETE uri ~headers >>= fun (resp, body) ->
    Request.handle_unit_response resp

let volume_inspect ~name =
    let open Lwt.Infix in
    let uri = Request.build_uri "/volumes/{name}" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "name" (fun x -> x) name in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Volume.of_yojson) resp body

let volume_list ?filters () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/volumes" in
    let headers = Request.default_headers in
    let uri = Request.maybe_add_query_param uri "filters" (fun x -> x) filters in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Volume_list_response.of_yojson) resp body

let volume_prune ?filters () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/volumes/prune" in
    let headers = Request.default_headers in
    let uri = Request.maybe_add_query_param uri "filters" (fun x -> x) filters in
    Cohttp_lwt_unix.Client.call `POST uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Volume_prune_response.of_yojson) resp body

