(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val volume_create : volume_config:Volume_create_options.t -> Volume.t Lwt.t
val volume_delete : name:string -> ?force:bool -> unit -> unit Lwt.t
val volume_inspect : name:string -> Volume.t Lwt.t
val volume_list : ?filters:string -> unit -> Volume_list_response.t Lwt.t
val volume_prune : ?filters:string -> unit -> Volume_prune_response.t Lwt.t
