(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    username: string option [@default None];
    password: string option [@default None];
    email: string option [@default None];
    serveraddress: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    username = None;
    password = None;
    email = None;
    serveraddress = None;
}

