(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string option [@default None];
    parent: string option [@default None];
    _type: string option [@default None];
    description: string option [@default None];
    in_use: bool option [@default None];
    shared: bool option [@default None];
    (* Amount of disk space used by the build cache (in bytes).  *)
    size: int32 option [@default None];
    (* Date and time at which the build cache was created in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  *)
    created_at: string option [@default None];
    (* Date and time at which the build cache was last used in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  *)
    last_used_at: string option [@default None];
    usage_count: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    id = None;
    parent = None;
    _type = None;
    description = None;
    in_use = None;
    shared = None;
    size = None;
    created_at = None;
    last_used_at = None;
    usage_count = None;
}

