(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string option [@default None];
    stream: string option [@default None];
    error: string option [@default None];
    error_detail: Error_detail.t option [@default None];
    status: string option [@default None];
    progress: string option [@default None];
    progress_detail: Progress_detail.t option [@default None];
    aux: Image_id.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    id = None;
    stream = None;
    error = None;
    error_detail = None;
    status = None;
    progress = None;
    progress_detail = None;
    aux = None;
}

