(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Commit.t : Commit holds the Git-commit (SHA1) that a binary was built from, as reported in the version-string of external tools, such as `containerd`, or `runC`. 
 *)

type t = {
    (* Actual commit ID of external tool. *)
    id: string option [@default None];
    (* Commit ID of external tool expected by dockerd as set at build time.  *)
    expected: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Commit holds the Git-commit (SHA1) that a binary was built from, as reported in the version-string of external tools, such as `containerd`, or `runC`.  *)
let create () : t = {
    id = None;
    expected = None;
}

