(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Container_wait_response.t : OK response to ContainerWait operation
 *)

type t = {
    (* Exit code of the container *)
    status_code: int32;
    error: Container_wait_exit_error.t;
} [@@deriving yojson { strict = false }, show ];;

(** OK response to ContainerWait operation *)
let create (status_code : int32) (error : Container_wait_exit_error.t) : t = {
    status_code = status_code;
    error = error;
}

