(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The ID of this container *)
    id: string option [@default None];
    (* The names that this container has been given *)
    names: string list;
    (* The name of the image used when creating this container *)
    image: string option [@default None];
    (* The ID of the image that this container was created from *)
    image_id: string option [@default None];
    (* Command to run when starting the container *)
    command: string option [@default None];
    (* When the container was created *)
    created: int64 option [@default None];
    (* The ports exposed by this container *)
    ports: Port.t list;
    (* The size of files that have been created or changed by this container *)
    size_rw: int64 option [@default None];
    (* The total size of all the files in this container *)
    size_root_fs: int64 option [@default None];
    (* User-defined key/value metadata. *)
    labels: (string * string) list;
    (* The state of this container (e.g. `Exited`) *)
    state: string option [@default None];
    (* Additional human-readable status of this container (e.g. `Exit 0`) *)
    status: string option [@default None];
    host_config: Container_summary_host_config.t option [@default None];
    network_settings: Container_summary_network_settings.t option [@default None];
    mounts: Mount_point.t list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    id = None;
    names = [];
    image = None;
    image_id = None;
    command = None;
    created = None;
    ports = [];
    size_rw = None;
    size_root_fs = None;
    labels = [];
    state = None;
    status = None;
    host_config = None;
    network_settings = None;
    mounts = [];
}

