(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Container_summary_network_settings.t : A summary of the container's network settings
 *)

type t = {
    networks: (string * Endpoint_settings.t) list;
} [@@deriving yojson { strict = false }, show ];;

(** A summary of the container's network settings *)
let create () : t = {
    networks = [];
}

