(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Container_wait_exit_error.t : container waiting error, if any
 *)

type t = {
    (* Details of an error *)
    message: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** container waiting error, if any *)
let create () : t = {
    message = None;
}

