(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Container_create_response.t : OK response to ContainerCreate operation
 *)

type t = {
    (* The ID of the created container *)
    id: string;
    (* Warnings encountered when creating the container *)
    warnings: string list;
} [@@deriving yojson { strict = false }, show ];;

(** OK response to ContainerCreate operation *)
let create (id : string) (warnings : string list) : t = {
    id = id;
    warnings = warnings;
}

