(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    host_config: Host_config.t option [@default None];
    networking_config: Networking_config.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    host_config = None;
    networking_config = None;
}

