(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The ID of the container *)
    id: string option [@default None];
    (* The time the container was created *)
    created: string option [@default None];
    (* The path to the command being run *)
    path: string option [@default None];
    (* The arguments to the command being run *)
    args: string list;
    state: Container_state.t option [@default None];
    (* The container's image ID *)
    image: string option [@default None];
    resolv_conf_path: string option [@default None];
    hostname_path: string option [@default None];
    hosts_path: string option [@default None];
    log_path: string option [@default None];
    name: string option [@default None];
    restart_count: int32 option [@default None];
    driver: string option [@default None];
    platform: string option [@default None];
    mount_label: string option [@default None];
    process_label: string option [@default None];
    app_armor_profile: string option [@default None];
    (* IDs of exec instances that are running in the container. *)
    exec_ids: string list;
    host_config: Host_config.t option [@default None];
    graph_driver: Graph_driver_data.t option [@default None];
    (* The size of files that have been created or changed by this container.  *)
    size_rw: int64 option [@default None];
    (* The total size of all the files in this container. *)
    size_root_fs: int64 option [@default None];
    mounts: Mount_point.t list;
    config: Container_config.t option [@default None];
    network_settings: Network_settings.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    id = None;
    created = None;
    path = None;
    args = [];
    state = None;
    image = None;
    resolv_conf_path = None;
    hostname_path = None;
    hosts_path = None;
    log_path = None;
    name = None;
    restart_count = None;
    driver = None;
    platform = None;
    mount_label = None;
    process_label = None;
    app_armor_profile = None;
    exec_ids = [];
    host_config = None;
    graph_driver = None;
    size_rw = None;
    size_root_fs = None;
    mounts = [];
    config = None;
    network_settings = None;
}

