(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Container_change_response_item.t : change item in response to ContainerChanges operation
 *)

type t = {
    (* Path to file that has changed *)
    path: string;
    (* Kind of change *)
    kind: int32;
} [@@deriving yojson { strict = false }, show ];;

(** change item in response to ContainerChanges operation *)
let create (path : string) (kind : int32) : t = {
    path = path;
    kind = kind;
}

