(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Device_mapping.t : A device mapping between the host and container
 *)

type t = {
    path_on_host: string option [@default None];
    path_in_container: string option [@default None];
    cgroup_permissions: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** A device mapping between the host and container *)
let create () : t = {
    path_on_host = None;
    path_in_container = None;
    cgroup_permissions = None;
}

