(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Distribution_inspect.t : Describes the result obtained from contacting the registry to retrieve image metadata. 
 *)

type t = {
    descriptor: Oci_descriptor.t;
    (* An array containing all platforms supported by the image.  *)
    platforms: Oci_platform.t list;
} [@@deriving yojson { strict = false }, show ];;

(** Describes the result obtained from contacting the registry to retrieve image metadata.  *)
let create (descriptor : Oci_descriptor.t) (platforms : Oci_platform.t list) : t = {
    descriptor = descriptor;
    platforms = platforms;
}

