(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Driver.t : Driver represents a driver (network, logging, secrets).
 *)

type t = {
    (* Name of the driver. *)
    name: string;
    (* Key/value map of driver-specific options. *)
    options: (string * string) list;
} [@@deriving yojson { strict = false }, show ];;

(** Driver represents a driver (network, logging, secrets). *)
let create (name : string) : t = {
    name = name;
    options = [];
}

