(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Endpoint_settings.t : Configuration for a network endpoint.
 *)

type t = {
    ipam_config: Endpoint_ipam_config.t option [@default None];
    links: string list;
    aliases: string list;
    (* Unique ID of the network.  *)
    network_id: string option [@default None];
    (* Unique ID for the service endpoint in a Sandbox.  *)
    endpoint_id: string option [@default None];
    (* Gateway address for this network.  *)
    gateway: string option [@default None];
    (* IPv4 address.  *)
    ip_address: string option [@default None];
    (* Mask length of the IPv4 address.  *)
    ip_prefix_len: int32 option [@default None];
    (* IPv6 gateway address.  *)
    ipv6_gateway: string option [@default None];
    (* Global IPv6 address.  *)
    global_ipv6_address: string option [@default None];
    (* Mask length of the global IPv6 address.  *)
    global_ipv6_prefix_len: int64 option [@default None];
    (* MAC address for the endpoint on this network.  *)
    mac_address: string option [@default None];
    (* DriverOpts is a mapping of driver options and values. These options are passed directly to the driver and are driver specific.  *)
    driver_opts: (string * string) list;
} [@@deriving yojson { strict = false }, show ];;

(** Configuration for a network endpoint. *)
let create () : t = {
    ipam_config = None;
    links = [];
    aliases = [];
    network_id = None;
    endpoint_id = None;
    gateway = None;
    ip_address = None;
    ip_prefix_len = None;
    ipv6_gateway = None;
    global_ipv6_address = None;
    global_ipv6_prefix_len = None;
    mac_address = None;
    driver_opts = [];
}

