(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Endpoint_spec.t : Properties that can be configured to access and load balance a service.
 *)

type t = {
    (* The mode of resolution to use for internal load balancing between tasks.  *)
    mode: Enums.mode option [@default Some(`Vip)];
    (* List of exposed ports that this service is accessible on from the outside. Ports can only be provided if `vip` resolution mode is used.  *)
    ports: Endpoint_port_config.t list;
} [@@deriving yojson { strict = false }, show ];;

(** Properties that can be configured to access and load balance a service. *)
let create () : t = {
    mode = None;
    ports = [];
}

