(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Engine_description.t : EngineDescription provides information about an engine.
 *)

type t = {
    engine_version: string option [@default None];
    labels: (string * string) list;
    plugins: Engine_description_plugins_inner.t list;
} [@@deriving yojson { strict = false }, show ];;

(** EngineDescription provides information about an engine. *)
let create () : t = {
    engine_version = None;
    labels = [];
    plugins = [];
}

