(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Error_response.t : Represents an error.
 *)

type t = {
    (* The error message. *)
    message: string;
} [@@deriving yojson { strict = false }, show ];;

(** Represents an error. *)
let create (message : string) : t = {
    message = message;
}

