(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Event_actor.t : Actor describes something that generates events, like a container, network, or a volume. 
 *)

type t = {
    (* The ID of the object emitting the event *)
    id: string option [@default None];
    (* Various key/value attributes of the object, depending on its type.  *)
    attributes: (string * string) list;
} [@@deriving yojson { strict = false }, show ];;

(** Actor describes something that generates events, like a container, network, or a volume.  *)
let create () : t = {
    id = None;
    attributes = [];
}

