(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Detach from the command. *)
    detach: bool option [@default None];
    (* Allocate a pseudo-TTY. *)
    tty: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    detach = None;
    tty = None;
}

