(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    can_remove: bool option [@default None];
    detach_keys: string option [@default None];
    id: string option [@default None];
    running: bool option [@default None];
    exit_code: int32 option [@default None];
    process_config: Process_config.t option [@default None];
    open_stdin: bool option [@default None];
    open_stderr: bool option [@default None];
    open_stdout: bool option [@default None];
    container_id: string option [@default None];
    (* The system process ID for the exec process. *)
    pid: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    can_remove = None;
    detach_keys = None;
    id = None;
    running = None;
    exit_code = None;
    process_config = None;
    open_stdin = None;
    open_stderr = None;
    open_stdout = None;
    container_id = None;
    pid = None;
}

