(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    named_resource_spec: Generic_resources_inner_named_resource_spec.t option [@default None];
    discrete_resource_spec: Generic_resources_inner_discrete_resource_spec.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    named_resource_spec = None;
    discrete_resource_spec = None;
}

