(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    kind: string option [@default None];
    value: int64 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    kind = None;
    value = None;
}

