(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Graph_driver_data.t : Information about the storage driver used to store the container's and image's filesystem. 
 *)

type t = {
    (* Name of the storage driver. *)
    name: string;
    (* Low-level storage metadata, provided as key/value pairs.  This information is driver-specific, and depends on the storage-driver in use, and should be used for informational purposes only.  *)
    data: (string * string) list;
} [@@deriving yojson { strict = false }, show ];;

(** Information about the storage driver used to store the container's and image's filesystem.  *)
let create (name : string) (data : (string * string) list) : t = {
    name = name;
    data = data;
}

