(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Health.t : Health stores information about the container's healthcheck results. 
 *)

type t = {
    (* Status is one of `none`, `starting`, `healthy` or `unhealthy`  - \''none\''      Indicates there is no healthcheck - \''starting\''  Starting indicates that the container is not yet ready - \''healthy\''   Healthy indicates that the container is running correctly - \''unhealthy\'' Unhealthy indicates that the container has a problem  *)
    status: Enums.status option [@default None];
    (* FailingStreak is the number of consecutive failures *)
    failing_streak: int32 option [@default None];
    (* Log contains the last few results (oldest first)  *)
    log: Healthcheck_result.t list;
} [@@deriving yojson { strict = false }, show ];;

(** Health stores information about the container's healthcheck results.  *)
let create () : t = {
    status = None;
    failing_streak = None;
    log = [];
}

