(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Health_config.t : A test to perform to check that the container is healthy.
 *)

type t = {
    (* The test to perform. Possible values are:  - `[]` inherit healthcheck from image or parent image - `[\''NONE\'']` disable healthcheck - `[\''CMD\'', args...]` exec arguments directly - `[\''CMD-SHELL\'', command]` run command with system's default shell  *)
    test: string list;
    (* The time to wait between checks in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.  *)
    interval: int32 option [@default None];
    (* The time to wait before considering the check to have hung. It should be 0 or at least 1000000 (1 ms). 0 means inherit.  *)
    timeout: int32 option [@default None];
    (* The number of consecutive failures needed to consider a container as unhealthy. 0 means inherit.  *)
    retries: int32 option [@default None];
    (* Start period for the container to initialize before starting health-retries countdown in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.  *)
    start_period: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** A test to perform to check that the container is healthy. *)
let create () : t = {
    test = [];
    interval = None;
    timeout = None;
    retries = None;
    start_period = None;
}

