(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema History_response_item.t : individual image layer information in response to ImageHistory operation
 *)

type t = {
    id: string;
    created: int64;
    created_by: string;
    tags: string list;
    size: int64;
    comment: string;
} [@@deriving yojson { strict = false }, show ];;

(** individual image layer information in response to ImageHistory operation *)
let create (id : string) (created : int64) (created_by : string) (tags : string list) (size : int64) (comment : string) : t = {
    id = id;
    created = created;
    created_by = created_by;
    tags = tags;
    size = size;
    comment = comment;
}

