(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Host_config_all_of_log_config.t : The logging configuration for this container
 *)

type t = {
    _type: Enums.hostconfig_allof_logconfig_type option [@default None];
    config: (string * string) list;
} [@@deriving yojson { strict = false }, show ];;

(** The logging configuration for this container *)
let create () : t = {
    _type = None;
    config = [];
}

