(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Image_inspect_metadata.t : Additional metadata of the image in the local cache. This information is local to the daemon, and not part of the image itself. 
 *)

type t = {
    (* Date and time at which the image was last tagged in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  This information is only available if the image was tagged locally, and omitted otherwise.  *)
    last_tag_time: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Additional metadata of the image in the local cache. This information is local to the daemon, and not part of the image itself.  *)
let create () : t = {
    last_tag_time = None;
}

