(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    parent_id: string;
    repo_tags: string list;
    repo_digests: string list;
    created: int32;
    size: int32;
    shared_size: int32;
    virtual_size: int32;
    labels: (string * string) list;
    containers: int32;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (parent_id : string) (repo_tags : string list) (repo_digests : string list) (created : int32) (size : int32) (shared_size : int32) (virtual_size : int32) (labels : (string * string) list) (containers : int32) : t = {
    id = id;
    parent_id = parent_id;
    repo_tags = repo_tags;
    repo_digests = repo_digests;
    created = created;
    size = size;
    shared_size = shared_size;
    virtual_size = virtual_size;
    labels = labels;
    containers = containers;
}

