(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Image_id.t : Image ID or Digest
 *)

type t = {
    id: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Image ID or Digest *)
let create () : t = {
    id = None;
}

