(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The image ID of an image that was untagged *)
    untagged: string option [@default None];
    (* The image ID of an image that was deleted *)
    deleted: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    untagged = None;
    deleted = None;
}

