(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Images that were deleted *)
    images_deleted: Image_delete_response_item.t list;
    (* Disk space reclaimed in bytes *)
    space_reclaimed: int64 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    images_deleted = [];
    space_reclaimed = None;
}

