(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Image_inspect.t : Information about an image in the local image cache. 
 *)

type t = {
    (* ID is the content-addressable ID of an image.  This identified is a content-addressable digest calculated from the image's configuration (which includes the digests of layers used by the image).  Note that this digest differs from the `RepoDigests` below, which holds digests of image manifests that reference the image.  *)
    id: string option [@default None];
    (* List of image names/tags in the local image cache that reference this image.  Multiple image tags can refer to the same imagem and this list may be empty if no tags reference the image, in which case the image is \''untagged\'', in which case it can still be referenced by its ID.  *)
    repo_tags: string list;
    (* List of content-addressable digests of locally available image manifests that the image is referenced from. Multiple manifests can refer to the same image.  These digests are usually only available if the image was either pulled from a registry, or if the image was pushed to a registry, which is when the manifest is generated and its digest calculated.  *)
    repo_digests: string list;
    (* ID of the parent image.  Depending on how the image was created, this field may be empty and is only set for images that were built/created locally. This field is empty if the image was pulled from an image registry.  *)
    parent: string option [@default None];
    (* Optional message that was set when committing or importing the image.  *)
    comment: string option [@default None];
    (* Date and time at which the image was created, formatted in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  *)
    created: string option [@default None];
    (* The ID of the container that was used to create the image.  Depending on how the image was created, this field may be empty.  *)
    container: string option [@default None];
    container_config: Container_config.t option [@default None];
    (* The version of Docker that was used to build the image.  Depending on how the image was created, this field may be empty.  *)
    docker_version: string option [@default None];
    (* Name of the author that was specified when committing the image, or as specified through MAINTAINER (deprecated) in the Dockerfile.  *)
    author: string option [@default None];
    config: Container_config.t option [@default None];
    (* Hardware CPU architecture that the image runs on.  *)
    architecture: string option [@default None];
    (* CPU architecture variant (presently ARM-only).  *)
    variant: string option [@default None];
    (* Operating System the image is built to run on.  *)
    os: string option [@default None];
    (* Operating System version the image is built to run on (especially for Windows).  *)
    os_version: string option [@default None];
    (* Total size of the image including all layers it is composed of.  *)
    size: int64 option [@default None];
    (* Total size of the image including all layers it is composed of.  In versions of Docker before v1.10, this field was calculated from the image itself and all of its parent images. Docker v1.10 and up store images self-contained, and no longer use a parent-chain, making this field an equivalent of the Size field.  This field is kept for backward compatibility, but may be removed in a future version of the API.  *)
    virtual_size: int64 option [@default None];
    graph_driver: Graph_driver_data.t option [@default None];
    root_fs: Image_inspect_root_fs.t option [@default None];
    metadata: Image_inspect_metadata.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Information about an image in the local image cache.  *)
let create () : t = {
    id = None;
    repo_tags = [];
    repo_digests = [];
    parent = None;
    comment = None;
    created = None;
    container = None;
    container_config = None;
    docker_version = None;
    author = None;
    config = None;
    architecture = None;
    variant = None;
    os = None;
    os_version = None;
    size = None;
    virtual_size = None;
    graph_driver = None;
    root_fs = None;
    metadata = None;
}

