(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Name of the IPAM driver to use. *)
    driver: string option [@default None];
    (* List of IPAM configuration options, specified as a map:  ``` {\''Subnet\'': <CIDR>, \''IPRange\'': <CIDR>, \''Gateway\'': <IP address>, \''AuxAddress\'': <device_name:IP address>} ```  *)
    config: Ipam_config.t list;
    (* Driver-specific options, specified as a map. *)
    options: (string * string) list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    driver = None;
    config = [];
    options = [];
}

