(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    subnet: string option [@default None];
    ip_range: string option [@default None];
    gateway: string option [@default None];
    auxiliary_addresses: (string * string) list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    subnet = None;
    ip_range = None;
    gateway = None;
    auxiliary_addresses = [];
}

