(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Join_tokens.t : JoinTokens contains the tokens workers and managers need to join the swarm. 
 *)

type t = {
    (* The token workers can use to join the swarm.  *)
    worker: string option [@default None];
    (* The token managers can use to join the swarm.  *)
    manager: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** JoinTokens contains the tokens workers and managers need to join the swarm.  *)
let create () : t = {
    worker = None;
    manager = None;
}

