(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Limit.t : An object describing a limit on resources which can be requested by a task. 
 *)

type t = {
    nano_cpus: int64 option [@default None];
    memory_bytes: int64 option [@default None];
    (* Limits the maximum number of PIDs in the container. Set `0` for unlimited.  *)
    pids: int64 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** An object describing a limit on resources which can be requested by a task.  *)
let create () : t = {
    nano_cpus = None;
    memory_bytes = None;
    pids = None;
}

