(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Container path. *)
    target: string option [@default None];
    (* Mount source (e.g. a volume name, a host path). *)
    source: string option [@default None];
    (* The mount type. Available types:  - `bind` Mounts a file or directory from the host into the container. Must exist prior to creating the container. - `volume` Creates a volume with the given name and options (or uses a pre-existing volume with the same name and options). These are **not** removed when the container is removed. - `tmpfs` Create a tmpfs with the given options. The mount source cannot be specified for tmpfs. - `npipe` Mounts a named pipe from the host into the container. Must exist prior to creating the container.  *)
    _type: Enums.mountpoint_type option [@default None];
    (* Whether the mount should be read-only. *)
    read_only: bool option [@default None];
    (* The consistency requirement for the mount: `default`, `consistent`, `cached`, or `delegated`. *)
    consistency: string option [@default None];
    bind_options: Mount_bind_options.t option [@default None];
    volume_options: Mount_volume_options.t option [@default None];
    tmpfs_options: Mount_tmpfs_options.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    target = None;
    source = None;
    _type = None;
    read_only = None;
    consistency = None;
    bind_options = None;
    volume_options = None;
    tmpfs_options = None;
}

