(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Mount_volume_options_driver_config.t : Map of driver specific options
 *)

type t = {
    (* Name of the driver to use to create the volume. *)
    name: string option [@default None];
    (* key/value map of driver specific options. *)
    options: (string * string) list;
} [@@deriving yojson { strict = false }, show ];;

(** Map of driver specific options *)
let create () : t = {
    name = None;
    options = [];
}

