(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Mount_volume_options.t : Optional configuration for the `volume` type.
 *)

type t = {
    (* Populate volume with data from the target. *)
    no_copy: bool option [@default None];
    (* User-defined key/value metadata. *)
    labels: (string * string) list;
    driver_config: Mount_volume_options_driver_config.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Optional configuration for the `volume` type. *)
let create () : t = {
    no_copy = None;
    labels = [];
    driver_config = None;
}

