(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Mount_tmpfs_options.t : Optional configuration for the `tmpfs` type.
 *)

type t = {
    (* The size for the tmpfs mount in bytes. *)
    size_bytes: int64 option [@default None];
    (* The permission mode for the tmpfs mount in an integer. *)
    mode: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Optional configuration for the `tmpfs` type. *)
let create () : t = {
    size_bytes = None;
    mode = None;
}

