(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Mount_point.t : MountPoint represents a mount point configuration inside the container. This is used for reporting the mountpoints in use by a container. 
 *)

type t = {
    (* The mount type:  - `bind` a mount of a file or directory from the host into the container. - `volume` a docker volume with the given `Name`. - `tmpfs` a `tmpfs`. - `npipe` a named pipe from the host into the container.  *)
    _type: Enums.mountpoint_type option [@default None];
    (* Name is the name reference to the underlying data defined by `Source` e.g., the volume name.  *)
    name: string option [@default None];
    (* Source location of the mount.  For volumes, this contains the storage location of the volume (within `/var/lib/docker/volumes/`). For bind-mounts, and `npipe`, this contains the source (host) part of the bind-mount. For `tmpfs` mount points, this field is empty.  *)
    source: string option [@default None];
    (* Destination is the path relative to the container root (`/`) where the `Source` is mounted inside the container.  *)
    destination: string option [@default None];
    (* Driver is the volume driver used to create the volume (if it is a volume).  *)
    driver: string option [@default None];
    (* Mode is a comma separated list of options supplied by the user when creating the bind/volume mount.  The default is platform-specific (`\''z\''` on Linux, empty on Windows).  *)
    mode: string option [@default None];
    (* Whether the mount is mounted writable (read-write).  *)
    rw: bool option [@default None];
    (* Propagation describes how mounts are propagated from the host into the mount point, and vice-versa. Refer to the [Linux kernel documentation](https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt) for details. This field is not used on Windows.  *)
    propagation: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** MountPoint represents a mount point configuration inside the container. This is used for reporting the mountpoints in use by a container.  *)
let create () : t = {
    _type = None;
    name = None;
    source = None;
    destination = None;
    driver = None;
    mode = None;
    rw = None;
    propagation = None;
}

