(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Networking_config.t : NetworkingConfig represents the container's networking configuration for each of its interfaces. It is used for the networking configs specified in the `docker create` and `docker network connect` commands. 
 *)

type t = {
    (* A mapping of network name to endpoint configuration for that network.  *)
    endpoints_config: (string * Endpoint_settings.t) list;
} [@@deriving yojson { strict = false }, show ];;

(** NetworkingConfig represents the container's networking configuration for each of its interfaces. It is used for the networking configs specified in the `docker create` and `docker network connect` commands.  *)
let create () : t = {
    endpoints_config = [];
}

