(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Network_attachment_config.t : Specifies how a service should be attached to a particular network. 
 *)

type t = {
    (* The target network for attachment. Must be a network name or ID.  *)
    target: string option [@default None];
    (* Discoverable alternate names for the service on this network.  *)
    aliases: string list;
    (* Driver attachment options for the network target.  *)
    driver_opts: (string * string) list;
} [@@deriving yojson { strict = false }, show ];;

(** Specifies how a service should be attached to a particular network.  *)
let create () : t = {
    target = None;
    aliases = [];
    driver_opts = [];
}

