(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Networks that were deleted *)
    networks_deleted: string list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    networks_deleted = [];
}

