(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    name: string option [@default None];
    endpoint_id: string option [@default None];
    mac_address: string option [@default None];
    ipv4_address: string option [@default None];
    ipv6_address: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    name = None;
    endpoint_id = None;
    mac_address = None;
    ipv4_address = None;
    ipv6_address = None;
}

