(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    name: string option [@default None];
    id: string option [@default None];
    created: string option [@default None];
    scope: string option [@default None];
    driver: string option [@default None];
    enable_ipv6: bool option [@default None];
    ipam: Ipam.t option [@default None];
    internal: bool option [@default None];
    attachable: bool option [@default None];
    ingress: bool option [@default None];
    containers: (string * Network_container.t) list;
    options: (string * string) list;
    labels: (string * string) list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    name = None;
    id = None;
    created = None;
    scope = None;
    driver = None;
    enable_ipv6 = None;
    ipam = None;
    internal = None;
    attachable = None;
    ingress = None;
    containers = [];
    options = [];
    labels = [];
}

