(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Node_status.t : NodeStatus represents the status of a node.  It provides the current status of the node, as seen by the manager. 
 *)

type t = {
    state: Enums.nodestate option [@default None];
    message: string option [@default None];
    (* IP address of the node. *)
    addr: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** NodeStatus represents the status of a node.  It provides the current status of the node, as seen by the manager.  *)
let create () : t = {
    state = None;
    message = None;
    addr = None;
}

