(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Name for the node. *)
    name: string option [@default None];
    (* User-defined key/value metadata. *)
    labels: (string * string) list;
    (* Role of the node. *)
    role: Enums.role option [@default None];
    (* Availability of the node. *)
    availability: Enums.availability option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    name = None;
    labels = [];
    role = None;
    availability = None;
}

