(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Oci_platform.t : Describes the platform which the image in the manifest runs on, as defined in the [OCI Image Index Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/image-index.md). 
 *)

type t = {
    (* The CPU architecture, for example `amd64` or `ppc64`.  *)
    architecture: string option [@default None];
    (* The operating system, for example `linux` or `windows`.  *)
    os: string option [@default None];
    (* Optional field specifying the operating system version, for example on Windows `10.0.19041.1165`.  *)
    os_version: string option [@default None];
    (* Optional field specifying an array of strings, each listing a required OS feature (for example on Windows `win32k`).  *)
    os_features: string list;
    (* Optional field specifying a variant of the CPU, for example `v7` to specify ARMv7 when architecture is `arm`.  *)
    variant: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Describes the platform which the image in the manifest runs on, as defined in the [OCI Image Index Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/image-index.md).  *)
let create () : t = {
    architecture = None;
    os = None;
    os_version = None;
    os_features = [];
    variant = None;
}

