(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Oci_descriptor.t : A descriptor struct containing digest, media type, and size, as defined in the [OCI Content Descriptors Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/descriptor.md). 
 *)

type t = {
    (* The media type of the object this schema refers to.  *)
    media_type: string option [@default None];
    (* The digest of the targeted content.  *)
    digest: string option [@default None];
    (* The size in bytes of the blob.  *)
    size: int64 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** A descriptor struct containing digest, media type, and size, as defined in the [OCI Content Descriptors Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/descriptor.md).  *)
let create () : t = {
    media_type = None;
    digest = None;
    size = None;
}

