(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Platform.t : Platform represents the platform (Arch/OS). 
 *)

type t = {
    (* Architecture represents the hardware architecture (for example, `x86_64`).  *)
    architecture: string option [@default None];
    (* OS represents the Operating System (for example, `linux` or `windows`).  *)
    os: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Platform represents the platform (Arch/OS).  *)
let create () : t = {
    architecture = None;
    os = None;
}

