(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    prefix: string;
    capability: string;
    version: string;
} [@@deriving yojson { strict = false }, show ];;

let create (prefix : string) (capability : string) (version : string) : t = {
    prefix = prefix;
    capability = capability;
    version = version;
}

