(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Plugins_info.t : Available plugins per type.  <p><br /></p>  > **Note**: Only unmanaged (V1) plugins are included in this list. > V1 plugins are \''lazily\'' loaded, and are not returned in this list > if there is no resource using the plugin. 
 *)

type t = {
    (* Names of available volume-drivers, and network-driver plugins. *)
    volume: string list;
    (* Names of available network-drivers, and network-driver plugins. *)
    network: string list;
    (* Names of available authorization plugins. *)
    authorization: string list;
    (* Names of available logging-drivers, and logging-driver plugins. *)
    log: string list;
} [@@deriving yojson { strict = false }, show ];;

(** Available plugins per type.  <p><br /></p>  > **Note**: Only unmanaged (V1) plugins are included in this list. > V1 plugins are \''lazily\'' loaded, and are not returned in this list > if there is no resource using the plugin.  *)
let create () : t = {
    volume = [];
    network = [];
    authorization = [];
    log = [];
}

