(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    capabilities: string list;
    allow_all_devices: bool;
    devices: Plugin_device.t list;
} [@@deriving yojson { strict = false }, show ];;

let create (capabilities : string list) (allow_all_devices : bool) (devices : Plugin_device.t list) : t = {
    capabilities = capabilities;
    allow_all_devices = allow_all_devices;
    devices = devices;
}

