(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    _type: string option [@default None];
    diff_ids: string list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    _type = None;
    diff_ids = [];
}

