(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Plugin_config.t : The config of a plugin.
 *)

type t = {
    (* Docker Version used to create the plugin *)
    docker_version: string option [@default None];
    description: string;
    documentation: string;
    interface: Plugin_config_interface.t;
    entrypoint: string list;
    work_dir: string;
    user: Plugin_config_user.t option [@default None];
    network: Plugin_config_network.t;
    linux: Plugin_config_linux.t;
    propagated_mount: string;
    ipc_host: bool;
    pid_host: bool;
    mounts: Plugin_mount.t list;
    env: Plugin_env.t list;
    args: Plugin_config_args.t;
    rootfs: Plugin_config_rootfs.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** The config of a plugin. *)
let create (description : string) (documentation : string) (interface : Plugin_config_interface.t) (entrypoint : string list) (work_dir : string) (network : Plugin_config_network.t) (linux : Plugin_config_linux.t) (propagated_mount : string) (ipc_host : bool) (pid_host : bool) (mounts : Plugin_mount.t list) (env : Plugin_env.t list) (args : Plugin_config_args.t) : t = {
    docker_version = None;
    description = description;
    documentation = documentation;
    interface = interface;
    entrypoint = entrypoint;
    work_dir = work_dir;
    user = None;
    network = network;
    linux = linux;
    propagated_mount = propagated_mount;
    ipc_host = ipc_host;
    pid_host = pid_host;
    mounts = mounts;
    env = env;
    args = args;
    rootfs = None;
}

