(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    name: string;
    description: string;
    settable: string list;
    path: string;
} [@@deriving yojson { strict = false }, show ];;

let create (name : string) (description : string) (settable : string list) (path : string) : t = {
    name = name;
    description = description;
    settable = settable;
    path = path;
}

