(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    name: string;
    description: string;
    settable: string list;
    source: string;
    destination: string;
    _type: string;
    options: string list;
} [@@deriving yojson { strict = false }, show ];;

let create (name : string) (description : string) (settable : string list) (source : string) (destination : string) (_type : string) (options : string list) : t = {
    name = name;
    description = description;
    settable = settable;
    source = source;
    destination = destination;
    _type = _type;
    options = options;
}

