(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Plugin_privilege.t : Describes a permission the user has to accept upon installing the plugin. 
 *)

type t = {
    name: string option [@default None];
    description: string option [@default None];
    value: string list;
} [@@deriving yojson { strict = false }, show ];;

(** Describes a permission the user has to accept upon installing the plugin.  *)
let create () : t = {
    name = None;
    description = None;
    value = [];
}

