(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Plugin_settings.t : Settings that can be modified by users.
 *)

type t = {
    mounts: Plugin_mount.t list;
    env: string list;
    args: string list;
    devices: Plugin_device.t list;
} [@@deriving yojson { strict = false }, show ];;

(** Settings that can be modified by users. *)
let create (mounts : Plugin_mount.t list) (env : string list) (args : string list) (devices : Plugin_device.t list) : t = {
    mounts = mounts;
    env = env;
    args = args;
    devices = devices;
}

