(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Port_binding.t : PortBinding represents a binding between a host IP address and a host port. 
 *)

type t = {
    (* Host IP address that the container's port is mapped to. *)
    host_ip: string option [@default None];
    (* Host port number that the container's port is mapped to. *)
    host_port: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** PortBinding represents a binding between a host IP address and a host port.  *)
let create () : t = {
    host_ip = None;
    host_port = None;
}

