(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Port.t : An open port on a container
 *)

type t = {
    (* Host IP address that the container's port is mapped to *)
    ip: string option [@default None];
    (* Port on the container *)
    private_port: int32;
    (* Port exposed on the host *)
    public_port: int32 option [@default None];
    _type: Enums.port_type;
} [@@deriving yojson { strict = false }, show ];;

(** An open port on a container *)
let create (private_port : int32) (_type : Enums.port_type) : t = {
    ip = None;
    private_port = private_port;
    public_port = None;
    _type = _type;
}

