(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    privileged: bool option [@default None];
    user: string option [@default None];
    tty: bool option [@default None];
    entrypoint: string option [@default None];
    arguments: string list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    privileged = None;
    user = None;
    tty = None;
    entrypoint = None;
    arguments = [];
}

