(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    error: string option [@default None];
    status: string option [@default None];
    progress: string option [@default None];
    progress_detail: Progress_detail.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    error = None;
    status = None;
    progress = None;
    progress_detail = None;
}

