(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Restart_policy.t : The behavior to apply when the container exits. The default is not to restart.  An ever increasing delay (double the previous delay, starting at 100ms) is added before each restart to prevent flooding the server. 
 *)

type t = {
    (* - Empty string means not to restart - `no` Do not automatically restart - `always` Always restart - `unless-stopped` Restart always except when the user has manually stopped the container - `on-failure` Restart only when the container exit code is non-zero  *)
    name: Enums.name option [@default None];
    (* If `on-failure` is used, the number of times to retry before giving up.  *)
    maximum_retry_count: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** The behavior to apply when the container exits. The default is not to restart.  An ever increasing delay (double the previous delay, starting at 100ms) is added before each restart to prevent flooding the server.  *)
let create () : t = {
    name = None;
    maximum_retry_count = None;
}

