(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Service_spec_mode_replicated_job.t : The mode used for services with a finite number of tasks that run to a completed state. 
 *)

type t = {
    (* The maximum number of replicas to run simultaneously.  *)
    max_concurrent: int64 option [@default None];
    (* The total number of replicas desired to reach the Completed state. If unset, will default to the value of `MaxConcurrent`  *)
    total_completions: int64 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** The mode used for services with a finite number of tasks that run to a completed state.  *)
let create () : t = {
    max_concurrent = None;
    total_completions = None;
}

