(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    spec: Endpoint_spec.t option [@default None];
    ports: Endpoint_port_config.t list;
    virtual_ips: Service_endpoint_virtual_ips_inner.t list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    spec = None;
    ports = [];
    virtual_ips = [];
}

