(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Service_spec_mode.t : Scheduling mode for the service.
 *)

type t = {
    replicated: Service_spec_mode_replicated.t option [@default None];
    global: Yojson.Safe.t option [@default None];
    replicated_job: Service_spec_mode_replicated_job.t option [@default None];
    (* The mode used for services which run a task to the completed state on each valid node.  *)
    global_job: Yojson.Safe.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Scheduling mode for the service. *)
let create () : t = {
    replicated = None;
    global = None;
    replicated_job = None;
    global_job = None;
}

