(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Service_spec.t : User modifiable configuration for a service.
 *)

type t = {
    (* Name of the service. *)
    name: string option [@default None];
    (* User-defined key/value metadata. *)
    labels: (string * string) list;
    task_template: Task_spec.t option [@default None];
    mode: Service_spec_mode.t option [@default None];
    update_config: Service_spec_update_config.t option [@default None];
    rollback_config: Service_spec_rollback_config.t option [@default None];
    (* Specifies which networks the service should attach to. *)
    networks: Network_attachment_config.t list;
    endpoint_spec: Endpoint_spec.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** User modifiable configuration for a service. *)
let create () : t = {
    name = None;
    labels = [];
    task_template = None;
    mode = None;
    update_config = None;
    rollback_config = None;
    networks = [];
    endpoint_spec = None;
}

