(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Optional warning messages *)
    warnings: string list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    warnings = [];
}

