(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Service_job_status.t : The status of the service when it is in one of ReplicatedJob or GlobalJob modes. Absent on Replicated and Global mode services. The JobIteration is an ObjectVersion, but unlike the Service's version, does not need to be sent with an update request. 
 *)

type t = {
    job_iteration: Object_version.t option [@default None];
    (* The last time, as observed by the server, that this job was started.  *)
    last_execution: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** The status of the service when it is in one of ReplicatedJob or GlobalJob modes. Absent on Replicated and Global mode services. The JobIteration is an ObjectVersion, but unlike the Service's version, does not need to be sent with an update request.  *)
let create () : t = {
    job_iteration = None;
    last_execution = None;
}

