(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Swarm_spec_encryption_config.t : Parameters related to encryption-at-rest.
 *)

type t = {
    (* If set, generate a key and use it to lock data stored on the managers.  *)
    auto_lock_managers: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Parameters related to encryption-at-rest. *)
let create () : t = {
    auto_lock_managers = None;
}

