(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Swarm_spec_orchestration.t : Orchestration configuration.
 *)

type t = {
    (* The number of historic tasks to keep per instance or node. If negative, never remove completed or failed tasks.  *)
    task_history_retention_limit: int64 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Orchestration configuration. *)
let create () : t = {
    task_history_retention_limit = None;
}

