(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Listen address used for inter-manager communication, as well as determining the networking interface used for the VXLAN Tunnel Endpoint (VTEP). This can either be an address/port combination in the form `192.168.1.1:4567`, or an interface followed by a port number, like `eth0:4567`. If the port number is omitted, the default swarm listening port is used.  *)
    listen_addr: string option [@default None];
    (* Externally reachable address advertised to other nodes. This can either be an address/port combination in the form `192.168.1.1:4567`, or an interface followed by a port number, like `eth0:4567`. If the port number is omitted, the port number from the listen address is used. If `AdvertiseAddr` is not specified, it will be automatically detected when possible.  *)
    advertise_addr: string option [@default None];
    (* Address or interface to use for data path traffic (format: `<ip|interface>`), for example,  `192.168.1.1`, or an interface, like `eth0`. If `DataPathAddr` is unspecified, the same address as `AdvertiseAddr` is used.  The `DataPathAddr` specifies the address that global scope network drivers will publish towards other  nodes in order to reach the containers running on this node. Using this parameter it is possible to separate the container data traffic from the management traffic of the cluster.  *)
    data_path_addr: string option [@default None];
    (* DataPathPort specifies the data path port number for data traffic. Acceptable port range is 1024 to 49151. if no port is set or is set to 0, default port 4789 will be used.  *)
    data_path_port: int32 option [@default None];
    (* Default Address Pool specifies default subnet pools for global scope networks.  *)
    default_addr_pool: string list;
    (* Force creation of a new swarm. *)
    force_new_cluster: bool option [@default None];
    (* SubnetSize specifies the subnet size of the networks created from the default subnet pool.  *)
    subnet_size: int32 option [@default None];
    spec: Swarm_spec.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    listen_addr = None;
    advertise_addr = None;
    data_path_addr = None;
    data_path_port = None;
    default_addr_pool = [];
    force_new_cluster = None;
    subnet_size = None;
    spec = None;
}

