(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Swarm_spec_ca_config.t : CA configuration.
 *)

type t = {
    (* The duration node certificates are issued for. *)
    node_cert_expiry: int64 option [@default None];
    (* Configuration for forwarding signing requests to an external certificate authority.  *)
    external_cas: Swarm_spec_ca_config_external_cas_inner.t list;
    (* The desired signing CA certificate for all swarm node TLS leaf certificates, in PEM format.  *)
    signing_ca_cert: string option [@default None];
    (* The desired signing CA key for all swarm node TLS leaf certificates, in PEM format.  *)
    signing_ca_key: string option [@default None];
    (* An integer whose purpose is to force swarm to generate a new signing CA certificate and key, if none have been specified in `SigningCACert` and `SigningCAKey`  *)
    force_rotate: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** CA configuration. *)
let create () : t = {
    node_cert_expiry = None;
    external_cas = [];
    signing_ca_cert = None;
    signing_ca_key = None;
    force_rotate = None;
}

