(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Swarm_info.t : Represents generic information about swarm. 
 *)

type t = {
    (* Unique identifier of for this node in the swarm. *)
    node_id: string option [@default None];
    (* IP address at which this node can be reached by other nodes in the swarm.  *)
    node_addr: string option [@default None];
    local_node_state: Enums.localnodestate option [@default None];
    control_available: bool option [@default None];
    error: string option [@default None];
    (* List of ID's and addresses of other managers in the swarm.  *)
    remote_managers: Peer_node.t list;
    (* Total number of nodes in the swarm. *)
    nodes: int32 option [@default None];
    (* Total number of managers in the swarm. *)
    managers: int32 option [@default None];
    cluster: Cluster_info.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Represents generic information about swarm.  *)
let create () : t = {
    node_id = None;
    node_addr = None;
    local_node_state = None;
    control_available = None;
    error = None;
    remote_managers = [];
    nodes = None;
    managers = None;
    cluster = None;
}

