(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The ID of the swarm. *)
    id: string option [@default None];
    version: Object_version.t option [@default None];
    (* Date and time at which the swarm was initialised in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  *)
    created_at: string option [@default None];
    (* Date and time at which the swarm was last updated in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  *)
    updated_at: string option [@default None];
    spec: Swarm_spec.t option [@default None];
    tls_info: Tls_info.t option [@default None];
    (* Whether there is currently a root CA rotation in progress for the swarm  *)
    root_rotation_in_progress: bool option [@default None];
    (* DataPathPort specifies the data path port number for data traffic. Acceptable port range is 1024 to 49151. If no port is set or is set to 0, the default port (4789) is used.  *)
    data_path_port: int32 option [@default None];
    (* Default Address Pool specifies default subnet pools for global scope networks.  *)
    default_addr_pool: string list;
    (* SubnetSize specifies the subnet size of the networks created from the default subnet pool.  *)
    subnet_size: int32 option [@default None];
    join_tokens: Join_tokens.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    id = None;
    version = None;
    created_at = None;
    updated_at = None;
    spec = None;
    tls_info = None;
    root_rotation_in_progress = None;
    data_path_port = None;
    default_addr_pool = [];
    subnet_size = None;
    join_tokens = None;
}

