(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Swarm_spec_raft.t : Raft configuration.
 *)

type t = {
    (* The number of log entries between snapshots. *)
    snapshot_interval: int32 option [@default None];
    (* The number of snapshots to keep beyond the current snapshot.  *)
    keep_old_snapshots: int32 option [@default None];
    (* The number of log entries to keep around to sync up slow followers after a snapshot is created.  *)
    log_entries_for_slow_followers: int32 option [@default None];
    (* The number of ticks that a follower will wait for a message from the leader before becoming a candidate and starting an election. `ElectionTick` must be greater than `HeartbeatTick`.  A tick currently defaults to one second, so these translate directly to seconds currently, but this is NOT guaranteed.  *)
    election_tick: int32 option [@default None];
    (* The number of ticks between heartbeats. Every HeartbeatTick ticks, the leader will send a heartbeat to the followers.  A tick currently defaults to one second, so these translate directly to seconds currently, but this is NOT guaranteed.  *)
    heartbeat_tick: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Raft configuration. *)
let create () : t = {
    snapshot_interval = None;
    keep_old_snapshots = None;
    log_entries_for_slow_followers = None;
    election_tick = None;
    heartbeat_tick = None;
}

