(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Protocol for communication with the external CA (currently only `cfssl` is supported).  *)
    protocol: Enums.protocol option [@default Some(`Cfssl)];
    (* URL where certificate signing requests should be sent.  *)
    url: string option [@default None];
    (* An object with key/value pairs that are interpreted as protocol-specific options for the external CA driver.  *)
    options: (string * string) list;
    (* The root CA certificate (in PEM format) this external CA uses to issue TLS certificates (assumed to be to the current swarm root CA certificate if not provided).  *)
    ca_cert: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    protocol = None;
    url = None;
    options = [];
    ca_cert = None;
}

