(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Unique identifier of the daemon.  <p><br /></p>  > **Note**: The format of the ID itself is not part of the API, and > should not be considered stable.  *)
    id: string option [@default None];
    (* Total number of containers on the host. *)
    containers: int32 option [@default None];
    (* Number of containers with status `\''running\''`.  *)
    containers_running: int32 option [@default None];
    (* Number of containers with status `\''paused\''`.  *)
    containers_paused: int32 option [@default None];
    (* Number of containers with status `\''stopped\''`.  *)
    containers_stopped: int32 option [@default None];
    (* Total number of images on the host.  Both _tagged_ and _untagged_ (dangling) images are counted.  *)
    images: int32 option [@default None];
    (* Name of the storage driver in use. *)
    driver: string option [@default None];
    (* Information specific to the storage driver, provided as \''label\'' / \''value\'' pairs.  This information is provided by the storage driver, and formatted in a way consistent with the output of `docker info` on the command line.  <p><br /></p>  > **Note**: The information returned in this field, including the > formatting of values and labels, should not be considered stable, > and may change without notice.  *)
    driver_status: string list list;
    (* Root directory of persistent Docker state.  Defaults to `/var/lib/docker` on Linux, and `C:\\ProgramData\\docker` on Windows.  *)
    docker_root_dir: string option [@default None];
    plugins: Plugins_info.t option [@default None];
    (* Indicates if the host has memory limit support enabled. *)
    memory_limit: bool option [@default None];
    (* Indicates if the host has memory swap limit support enabled. *)
    swap_limit: bool option [@default None];
    (* Indicates if the host has kernel memory limit support enabled.  <p><br /></p>  > **Deprecated**: This field is deprecated as the kernel 5.4 deprecated > `kmem.limit_in_bytes`.  *)
    kernel_memory: bool option [@default None];
    (* Indicates if the host has kernel memory TCP limit support enabled.  Kernel memory TCP limits are not supported when using cgroups v2, which does not support the corresponding `memory.kmem.tcp.limit_in_bytes` cgroup.  *)
    kernel_memory_tcp: bool option [@default None];
    (* Indicates if CPU CFS(Completely Fair Scheduler) period is supported by the host.  *)
    cpu_cfs_period: bool option [@default None];
    (* Indicates if CPU CFS(Completely Fair Scheduler) quota is supported by the host.  *)
    cpu_cfs_quota: bool option [@default None];
    (* Indicates if CPU Shares limiting is supported by the host.  *)
    cpu_shares: bool option [@default None];
    (* Indicates if CPUsets (cpuset.cpus, cpuset.mems) are supported by the host.  See [cpuset(7)](https://www.kernel.org/doc/Documentation/cgroup-v1/cpusets.txt)  *)
    cpu_set: bool option [@default None];
    (* Indicates if the host kernel has PID limit support enabled. *)
    pids_limit: bool option [@default None];
    (* Indicates if OOM killer disable is supported on the host. *)
    oom_kill_disable: bool option [@default None];
    (* Indicates IPv4 forwarding is enabled. *)
    ipv4_forwarding: bool option [@default None];
    (* Indicates if `bridge-nf-call-iptables` is available on the host. *)
    bridge_nf_iptables: bool option [@default None];
    (* Indicates if `bridge-nf-call-ip6tables` is available on the host. *)
    bridge_nf_ip6tables: bool option [@default None];
    (* Indicates if the daemon is running in debug-mode / with debug-level logging enabled.  *)
    debug: bool option [@default None];
    (* The total number of file Descriptors in use by the daemon process.  This information is only returned if debug-mode is enabled.  *)
    nfd: int32 option [@default None];
    (* The  number of goroutines that currently exist.  This information is only returned if debug-mode is enabled.  *)
    n_goroutines: int32 option [@default None];
    (* Current system-time in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  *)
    system_time: string option [@default None];
    (* The logging driver to use as a default for new containers.  *)
    logging_driver: string option [@default None];
    (* The driver to use for managing cgroups.  *)
    cgroup_driver: Enums.cgroupdriver option [@default Some(`Cgroupfs)];
    (* The version of the cgroup.  *)
    cgroup_version: Enums.cgroupversion option [@default Some(`_1)];
    (* Number of event listeners subscribed. *)
    n_events_listener: int32 option [@default None];
    (* Kernel version of the host.  On Linux, this information obtained from `uname`. On Windows this information is queried from the <kbd>HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\</kbd> registry value, for example _\''10.0 14393 (14393.1198.amd64fre.rs1_release_sec.170427-1353)\''_.  *)
    kernel_version: string option [@default None];
    (* Name of the host's operating system, for example: \''Ubuntu 16.04.2 LTS\'' or \''Windows Server 2016 Datacenter\''  *)
    operating_system: string option [@default None];
    (* Version of the host's operating system  <p><br /></p>  > **Note**: The information returned in this field, including its > very existence, and the formatting of values, should not be considered > stable, and may change without notice.  *)
    os_version: string option [@default None];
    (* Generic type of the operating system of the host, as returned by the Go runtime (`GOOS`).  Currently returned values are \''linux\'' and \''windows\''. A full list of possible values can be found in the [Go documentation](https://golang.org/doc/install/source#environment).  *)
    os_type: string option [@default None];
    (* Hardware architecture of the host, as returned by the Go runtime (`GOARCH`).  A full list of possible values can be found in the [Go documentation](https://golang.org/doc/install/source#environment).  *)
    architecture: string option [@default None];
    (* The number of logical CPUs usable by the daemon.  The number of available CPUs is checked by querying the operating system when the daemon starts. Changes to operating system CPU allocation after the daemon is started are not reflected.  *)
    ncpu: int32 option [@default None];
    (* Total amount of physical memory available on the host, in bytes.  *)
    mem_total: int64 option [@default None];
    (* Address / URL of the index server that is used for image search, and as a default for user authentication for Docker Hub and Docker Cloud.  *)
    index_server_address: string option [@default None];
    registry_config: Registry_service_config.t option [@default None];
    (* User-defined resources can be either Integer resources (e.g, `SSD=3`) or String resources (e.g, `GPU=UUID1`).  *)
    generic_resources: Generic_resources_inner.t list;
    (* HTTP-proxy configured for the daemon. This value is obtained from the [`HTTP_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable. Credentials ([user info component](https://tools.ietf.org/html/rfc3986#section-3.2.1)) in the proxy URL are masked in the API response.  Containers do not automatically inherit this configuration.  *)
    http_proxy: string option [@default None];
    (* HTTPS-proxy configured for the daemon. This value is obtained from the [`HTTPS_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable. Credentials ([user info component](https://tools.ietf.org/html/rfc3986#section-3.2.1)) in the proxy URL are masked in the API response.  Containers do not automatically inherit this configuration.  *)
    https_proxy: string option [@default None];
    (* Comma-separated list of domain extensions for which no proxy should be used. This value is obtained from the [`NO_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable.  Containers do not automatically inherit this configuration.  *)
    no_proxy: string option [@default None];
    (* Hostname of the host. *)
    name: string option [@default None];
    (* User-defined labels (key/value metadata) as set on the daemon.  <p><br /></p>  > **Note**: When part of a Swarm, nodes can both have _daemon_ labels, > set through the daemon configuration, and _node_ labels, set from a > manager node in the Swarm. Node labels are not included in this > field. Node labels can be retrieved using the `/nodes/(id)` endpoint > on a manager node in the Swarm.  *)
    labels: string list;
    (* Indicates if experimental features are enabled on the daemon.  *)
    experimental_build: bool option [@default None];
    (* Version string of the daemon.  > **Note**: the [standalone Swarm API](/swarm/swarm-api/) > returns the Swarm version instead of the daemon  version, for example > `swarm/1.2.8`.  *)
    server_version: string option [@default None];
    (* URL of the distributed storage backend.   The storage backend is used for multihost networking (to store network and endpoint information) and by the node discovery mechanism.  <p><br /></p>  > **Deprecated**: This field is only propagated when using standalone Swarm > mode, and overlay networking using an external k/v store. Overlay > networks with Swarm mode enabled use the built-in raft store, and > this field will be empty.  *)
    cluster_store: string option [@default None];
    (* The network endpoint that the Engine advertises for the purpose of node discovery. ClusterAdvertise is a `host:port` combination on which the daemon is reachable by other hosts.  <p><br /></p>  > **Deprecated**: This field is only propagated when using standalone Swarm > mode, and overlay networking using an external k/v store. Overlay > networks with Swarm mode enabled use the built-in raft store, and > this field will be empty.  *)
    cluster_advertise: string option [@default None];
    (* List of [OCI compliant](https://github.com/opencontainers/runtime-spec) runtimes configured on the daemon. Keys hold the \''name\'' used to reference the runtime.  The Docker daemon relies on an OCI compliant runtime (invoked via the `containerd` daemon) as its interface to the Linux kernel namespaces, cgroups, and SELinux.  The default runtime is `runc`, and automatically configured. Additional runtimes can be configured by the user and will be listed here.  *)
    runtimes: (string * Runtime.t) list;
    (* Name of the default OCI runtime that is used when starting containers.  The default can be overridden per-container at create time.  *)
    default_runtime: string option [@default None];
    swarm: Swarm_info.t option [@default None];
    (* Indicates if live restore is enabled.  If enabled, containers are kept running when the daemon is shutdown or upon daemon start if running containers are detected.  *)
    live_restore_enabled: bool option [@default None];
    (* Represents the isolation technology to use as a default for containers. The supported values are platform-specific.  If no isolation value is specified on daemon start, on Windows client, the default is `hyperv`, and on Windows server, the default is `process`.  This option is currently not used on other platforms.  *)
    isolation: Enums.systeminfo_isolation option [@default Some(`Default)];
    (* Name and, optional, path of the `docker-init` binary.  If the path is omitted, the daemon searches the host's `$PATH` for the binary and uses the first result.  *)
    init_binary: string option [@default None];
    containerd_commit: Commit.t option [@default None];
    runc_commit: Commit.t option [@default None];
    init_commit: Commit.t option [@default None];
    (* List of security features that are enabled on the daemon, such as apparmor, seccomp, SELinux, user-namespaces (userns), and rootless.  Additional configuration options for each security feature may be present, and are included as a comma-separated list of key/value pairs.  *)
    security_options: string list;
    (* Reports a summary of the product license on the daemon.  If a commercial license has been applied to the daemon, information such as number of nodes, and expiration are included.  *)
    product_license: string option [@default None];
    (* List of custom default address pools for local networks, which can be specified in the daemon.json file or dockerd option.  Example: a Base \''10.10.0.0/16\'' with Size 24 will define the set of 256 10.10.[0-255].0/24 address pools.  *)
    default_address_pools: System_info_default_address_pools_inner.t list;
    (* List of warnings / informational messages about missing features, or issues related to the daemon configuration.  These messages can be printed by the client as information to the user.  *)
    warnings: string list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    id = None;
    containers = None;
    containers_running = None;
    containers_paused = None;
    containers_stopped = None;
    images = None;
    driver = None;
    driver_status = [];
    docker_root_dir = None;
    plugins = None;
    memory_limit = None;
    swap_limit = None;
    kernel_memory = None;
    kernel_memory_tcp = None;
    cpu_cfs_period = None;
    cpu_cfs_quota = None;
    cpu_shares = None;
    cpu_set = None;
    pids_limit = None;
    oom_kill_disable = None;
    ipv4_forwarding = None;
    bridge_nf_iptables = None;
    bridge_nf_ip6tables = None;
    debug = None;
    nfd = None;
    n_goroutines = None;
    system_time = None;
    logging_driver = None;
    cgroup_driver = None;
    cgroup_version = None;
    n_events_listener = None;
    kernel_version = None;
    operating_system = None;
    os_version = None;
    os_type = None;
    architecture = None;
    ncpu = None;
    mem_total = None;
    index_server_address = None;
    registry_config = None;
    generic_resources = [];
    http_proxy = None;
    https_proxy = None;
    no_proxy = None;
    name = None;
    labels = [];
    experimental_build = None;
    server_version = None;
    cluster_store = None;
    cluster_advertise = None;
    runtimes = [];
    default_runtime = None;
    swarm = None;
    live_restore_enabled = None;
    isolation = None;
    init_binary = None;
    containerd_commit = None;
    runc_commit = None;
    init_commit = None;
    security_options = [];
    product_license = None;
    default_address_pools = [];
    warnings = [];
}

