(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The network address in CIDR format *)
    base: string option [@default None];
    (* The network pool size *)
    size: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    base = None;
    size = None;
}

