(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema System_version.t : Response of Engine API: GET \''/version\'' 
 *)

type t = {
    platform: System_version_platform.t option [@default None];
    (* Information about system components  *)
    components: System_version_components_inner.t list;
    (* The version of the daemon *)
    version: string option [@default None];
    (* The default (and highest) API version that is supported by the daemon  *)
    api_version: string option [@default None];
    (* The minimum API version that is supported by the daemon  *)
    min_api_version: string option [@default None];
    (* The Git commit of the source code that was used to build the daemon  *)
    git_commit: string option [@default None];
    (* The version Go used to compile the daemon, and the version of the Go runtime in use.  *)
    go_version: string option [@default None];
    (* The operating system that the daemon is running on (\''linux\'' or \''windows\'')  *)
    os: string option [@default None];
    (* The architecture that the daemon is running on  *)
    arch: string option [@default None];
    (* The kernel version (`uname -r`) that the daemon is running on.  This field is omitted when empty.  *)
    kernel_version: string option [@default None];
    (* Indicates if the daemon is started with experimental features enabled.  This field is omitted when empty / false.  *)
    experimental: bool option [@default None];
    (* The date and time that the daemon was compiled.  *)
    build_time: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Response of Engine API: GET \''/version\''  *)
let create () : t = {
    platform = None;
    components = [];
    version = None;
    api_version = None;
    min_api_version = None;
    git_commit = None;
    go_version = None;
    os = None;
    arch = None;
    kernel_version = None;
    experimental = None;
    build_time = None;
}

