(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    layers_size: int64 option [@default None];
    images: Image_summary.t list;
    containers: Container_summary.t list;
    volumes: Volume.t list;
    build_cache: Build_cache.t list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    layers_size = None;
    images = [];
    containers = [];
    volumes = [];
    build_cache = [];
}

