(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    name: string;
} [@@deriving yojson { strict = false }, show ];;

let create (name : string) : t = {
    name = name;
}

