(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* label descriptor, such as `engine.labels.az`.  *)
    spread_descriptor: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    spread_descriptor = None;
}

