(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    file: Task_spec_container_spec_secrets_inner_file.t option [@default None];
    (* SecretID represents the ID of the specific secret that we're referencing.  *)
    secret_id: string option [@default None];
    (* SecretName is the name of the secret that this references, but this is just provided for lookup/display purposes. The secret in the reference will be identified by its ID.  *)
    secret_name: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    file = None;
    secret_id = None;
    secret_name = None;
}

