(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Task_spec_container_spec_privileges.t : Security options for the container
 *)

type t = {
    credential_spec: Task_spec_container_spec_privileges_credential_spec.t option [@default None];
    se_linux_context: Task_spec_container_spec_privileges_se_linux_context.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Security options for the container *)
let create () : t = {
    credential_spec = None;
    se_linux_context = None;
}

