(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Task_spec_plugin_spec.t : Plugin spec for the service.  *(Experimental release only.)*  <p><br /></p>  > **Note**: ContainerSpec, NetworkAttachmentSpec, and PluginSpec are > mutually exclusive. PluginSpec is only used when the Runtime field > is set to `plugin`. NetworkAttachmentSpec is used when the Runtime > field is set to `attachment`. 
 *)

type t = {
    (* The name or 'alias' to use for the plugin. *)
    name: string option [@default None];
    (* The plugin image reference to use. *)
    remote: string option [@default None];
    (* Disable the plugin once scheduled. *)
    disabled: bool option [@default None];
    plugin_privilege: Plugin_privilege.t list;
} [@@deriving yojson { strict = false }, show ];;

(** Plugin spec for the service.  *(Experimental release only.)*  <p><br /></p>  > **Note**: ContainerSpec, NetworkAttachmentSpec, and PluginSpec are > mutually exclusive. PluginSpec is only used when the Runtime field > is set to `plugin`. NetworkAttachmentSpec is used when the Runtime > field is set to `attachment`.  *)
let create () : t = {
    name = None;
    remote = None;
    disabled = None;
    plugin_privilege = [];
}

