(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Task_spec_restart_policy.t : Specification for the restart policy which applies to containers created as part of this service. 
 *)

type t = {
    (* Condition for restart. *)
    condition: Enums.condition option [@default None];
    (* Delay between restart attempts. *)
    delay: int64 option [@default None];
    (* Maximum attempts to restart a given container before giving up (default value is 0, which is ignored).  *)
    max_attempts: int64 option [@default None];
    (* Windows is the time window used to evaluate the restart policy (default value is 0, which is unbounded).  *)
    window: int64 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Specification for the restart policy which applies to containers created as part of this service.  *)
let create () : t = {
    condition = None;
    delay = None;
    max_attempts = None;
    window = None;
}

