(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Task_spec_container_spec_secrets_inner_file.t : File represents a specific target that is backed by a file. 
 *)

type t = {
    (* Name represents the final filename in the filesystem.  *)
    name: string option [@default None];
    (* UID represents the file UID. *)
    uid: string option [@default None];
    (* GID represents the file GID. *)
    gid: string option [@default None];
    (* Mode represents the FileMode of the file. *)
    mode: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** File represents a specific target that is backed by a file.  *)
let create () : t = {
    name = None;
    uid = None;
    gid = None;
    mode = None;
}

