(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Task_spec_container_spec_dns_config.t : Specification for DNS related configurations in resolver configuration file (`resolv.conf`). 
 *)

type t = {
    (* The IP addresses of the name servers. *)
    nameservers: string list;
    (* A search list for host-name lookup. *)
    search: string list;
    (* A list of internal resolver variables to be modified (e.g., `debug`, `ndots:3`, etc.).  *)
    options: string list;
} [@@deriving yojson { strict = false }, show ];;

(** Specification for DNS related configurations in resolver configuration file (`resolv.conf`).  *)
let create () : t = {
    nameservers = [];
    search = [];
    options = [];
}

