(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Task_spec_log_driver.t : Specifies the log driver to use for tasks created from this spec. If not present, the default one for the swarm will be used, finally falling back to the engine default if not specified. 
 *)

type t = {
    name: string option [@default None];
    options: (string * string) list;
} [@@deriving yojson { strict = false }, show ];;

(** Specifies the log driver to use for tasks created from this spec. If not present, the default one for the swarm will be used, finally falling back to the engine default if not specified.  *)
let create () : t = {
    name = None;
    options = [];
}

