(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Task_spec_container_spec_privileges_se_linux_context.t : SELinux labels of the container
 *)

type t = {
    (* Disable SELinux *)
    disable: bool option [@default None];
    (* SELinux user label *)
    user: string option [@default None];
    (* SELinux role label *)
    role: string option [@default None];
    (* SELinux type label *)
    _type: string option [@default None];
    (* SELinux level label *)
    level: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** SELinux labels of the container *)
let create () : t = {
    disable = None;
    user = None;
    role = None;
    _type = None;
    level = None;
}

