(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Task_spec_resources.t : Resource requirements which apply to each individual container created as part of the service. 
 *)

type t = {
    limits: Limit.t option [@default None];
    reservations: Resource_object.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Resource requirements which apply to each individual container created as part of the service.  *)
let create () : t = {
    limits = None;
    reservations = None;
}

