(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    container_id: string option [@default None];
    pid: int32 option [@default None];
    exit_code: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    container_id = None;
    pid = None;
    exit_code = None;
}

