(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    file: Task_spec_container_spec_configs_inner_file.t option [@default None];
    (* Runtime represents a target that is not mounted into the container but is used by the task  <p><br /><p>  > **Note**: `Configs.File` and `Configs.Runtime` are mutually > exclusive  *)
    runtime: Yojson.Safe.t option [@default None];
    (* ConfigID represents the ID of the specific config that we're referencing.  *)
    config_id: string option [@default None];
    (* ConfigName is the name of the config that this references, but this is just provided for lookup/display purposes. The config in the reference will be identified by its ID.  *)
    config_name: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    file = None;
    runtime = None;
    config_id = None;
    config_name = None;
}

