(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Tls_info.t : Information about the issuer of leaf TLS certificates and the trusted root CA certificate. 
 *)

type t = {
    (* The root CA certificate(s) that are used to validate leaf TLS certificates.  *)
    trust_root: string option [@default None];
    (* The base64-url-safe-encoded raw subject bytes of the issuer. *)
    cert_issuer_subject: string option [@default None];
    (* The base64-url-safe-encoded raw public key bytes of the issuer.  *)
    cert_issuer_public_key: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Information about the issuer of leaf TLS certificates and the trusted root CA certificate.  *)
let create () : t = {
    trust_root = None;
    cert_issuer_subject = None;
    cert_issuer_public_key = None;
}

