(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Name of the volume. *)
    name: string;
    (* Name of the volume driver used by the volume. *)
    driver: string;
    (* Mount path of the volume on the host. *)
    mountpoint: string;
    (* Date/Time the volume was created. *)
    created_at: string option [@default None];
    (* Low-level details about the volume, provided by the volume driver. Details are returned as a map with key/value pairs: `{\''key\'':\''value\'',\''key2\'':\''value2\''}`.  The `Status` field is optional, and is omitted if the volume driver does not support this feature.  *)
    status: (string * Yojson.Safe.t) list;
    (* User-defined key/value metadata. *)
    labels: (string * string) list;
    (* The level at which the volume exists. Either `global` for cluster-wide, or `local` for machine level.  *)
    scope: Enums.volume_scope[@default `Local];
    (* The driver specific options used when creating the volume.  *)
    options: (string * string) list;
    usage_data: Volume_usage_data.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (name : string) (driver : string) (mountpoint : string) (labels : (string * string) list) (scope : Enums.volume_scope) (options : (string * string) list) : t = {
    name = name;
    driver = driver;
    mountpoint = mountpoint;
    created_at = None;
    status = [];
    labels = labels;
    scope = scope;
    options = options;
    usage_data = None;
}

