(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Volume_list_response.t : Volume list response
 *)

type t = {
    (* List of volumes *)
    volumes: Volume.t list;
    (* Warnings that occurred when fetching the list of volumes.  *)
    warnings: string list;
} [@@deriving yojson { strict = false }, show ];;

(** Volume list response *)
let create (volumes : Volume.t list) (warnings : string list) : t = {
    volumes = volumes;
    warnings = warnings;
}

